
# Kafka configuration
# kafka:
#   bootstrap-servers: localhost:9092
#   consumer:
#     group-id: bda-group
#     auto-offset-reset: earliest
#     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#     value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#   producer:
#     key-serializer: org.apache.kafka.common.serialization.StringSerializer
#     value-serializer: org.apache.kafka.common.serialization.StringSerializer
#     # additional kafka configurations
#     acks: all
#   consumer:
#     enable-auto-commit: false
#gRPC configuration
grpc:
  server:
    port: 5090
    enabled: false

base:
  encryption:
    key: Xn2r5u8x/A?D(G+K
    iv: 4654655168546825
    length: 256
    cipherAlgorithm: AES
    secretKeyFactory: PBKDF2WithHmacSHA512
    salt: 946565
    cipherInstance: AES/CBC/ISO10126Padding
    interactions: 65536

db:
  data:
    user: ${DATABASE_USER}
    pass: ${DATABASE_PASSWORD}
    driver: ${DATABASE_DRIVER}
    url: ${DATABASE_URL}