spring.application.name=customer-data
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.consumer.group-id=bda-group
#spring.kafka.consumer.auto-offset-reset=earliest
#
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Otras configuraciones opcionales que podrias necesitar
# spring.kafka.producer.acks=all
# spring.kafka.consumer.enable-auto-commit=false
spring.config.import=optional:configserver: instead.
grpc.server.port=9098

grpc.server.enabled=false

